# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZdlIPyyjOu8nmM4lLfqQOBW-HhYTsIC
"""

import streamlit as st
import tensorflow as tf
import os
import gdown
import cv2
import numpy as np
from PIL import Image

# --- CONFIGURATION ---
# The File ID from your Google Drive link
FILE_ID = '1hJk59rhCxpwdo9wfOq-WTY-gTVGcPsC9'
# UPDATED FILENAME
MODEL_FILENAME = 'asl_model_epoch_12.keras'
IMG_SIZE = 200

LABELS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
          'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
          'del', 'nothing', 'space']

# --- LOAD MODEL (With Auto-Download) ---
@st.cache_resource
def load_model():
    # 1. Download if missing
    if not os.path.exists(MODEL_FILENAME):
        url = f'https://drive.google.com/uc?id={FILE_ID}'
        gdown.download(url, MODEL_FILENAME, quiet=False)

    # 2. Load
    try:
        model = tf.keras.models.load_model(MODEL_FILENAME)
        return model
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

model = load_model()

# --- UI LAYOUT ---
st.title("🤟 ASL Sign Language Translator")
st.markdown("Upload an image of a hand sign, and the AI will translate it.")

# --- MAIN APP ---
if model is not None:
    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        # Display
        image = Image.open(uploaded_file)
        st.image(image, caption='Uploaded Image', width=300)
        st.write("Analyzing...")

        # Preprocess
        img_array = np.array(image.convert('RGB'))
        img_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
        img_array = img_array.astype('float32') / 255.0
        img_array = np.expand_dims(img_array, axis=0)

        # Predict
        predictions = model.predict(img_array)
        confidence = np.max(predictions)
        predicted_char = LABELS[np.argmax(predictions)]

        # Result
        st.success(f"Prediction: **{predicted_char}**")
        st.info(f"Confidence: {confidence * 10